"""add catalog_entries table

Revision ID: 5729719d7b21
Revises: 5729719d7b20
Create Date: 2026-03-03 19:27:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5729719d7b21'
down_revision: Union[str, None] = '5729719d7b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_entries_source_id'), 'catalog_entries', ['source_id'])
    op.create_index(op.f('ix_catalog_entries_table_name'), 'catalog_entries', ['source_id', 'table_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_entries_table_name'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_source_id'), table_name='catalog_entries')
    op.drop_table('catalog_entries')
    # ### end Alembic commands ###
