"""add settings table

Revision ID: 5729719d7b25
Revises: 5729719d7b24
Create Date: 2026-03-03 19:31:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5729719d7b25'
down_revision: Union[str, None] = '5729719d7b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'])
    op.create_index(op.f('ix_settings_workspace_id'), 'settings', ['workspace_id'])
    op.create_index(op.f('ix_settings_user_key'), 'settings', ['user_id', 'key'], unique=True)
    op.create_index(op.f('ix_settings_workspace_key'), 'settings', ['workspace_id', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_workspace_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_user_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_workspace_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
