"""add pipeline_versions table

Revision ID: 5729719d7b19
Revises: 5729719d7b18
Create Date: 2026-03-03 19:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5729719d7b19'
down_revision: Union[str, None] = '5729719d7b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_versions_pipeline_id'), 'pipeline_versions', ['pipeline_id'])
    op.create_index(op.f('ix_pipeline_versions_version'), 'pipeline_versions', ['pipeline_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_versions_version'), table_name='pipeline_versions')
    op.drop_index(op.f('ix_pipeline_versions_pipeline_id'), table_name='pipeline_versions')
    op.drop_table('pipeline_versions')
    # ### end Alembic commands ###
