"""add quality_rules table

Revision ID: 5729719d7b22
Revises: 5729719d7b21
Create Date: 2026-03-03 19:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5729719d7b22'
down_revision: Union[str, None] = '5729719d7b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_rules_workspace_id'), 'quality_rules', ['workspace_id'])
    op.create_index(op.f('ix_quality_rules_rule_type'), 'quality_rules', ['rule_type'])
    op.create_index(op.f('ix_quality_rules_enabled'), 'quality_rules', ['enabled'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_rules_enabled'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_rule_type'), table_name='quality_rules')
    op.drop_index(op.f('ix_quality_rules_workspace_id'), table_name='quality_rules')
    op.drop_table('quality_rules')
    # ### end Alembic commands ###
